version: "3"
services:
  python3:
    restart: always
    build: .
    container_name: "python3"
    working_dir: '/stock_app/'
    tty: true
    volumes:
     - ./output:/stock_app
  elasticsearch:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    environment:
     - xpack.security.enabled=false
     - "discovery.type=single-node"
    networks:
     - elastic
    ports:
     - 9200:9200
  kibana:
    container_name: kib-01
    image: docker.elastic.co/kibana/kibana:8.1.0
    environment:
     - ELASTICSEARCH_HOSTS=https://localhost:9200
    networks:
     - elastic
    depends_on:
     - elasticsearch
    ports:
     - 5601:5601
networks:
  elastic:
    driver: bridge
